server:
  port: 8090
spring:
  application:
    name: bolo-auth-service
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 9
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        heartbeat: # 开启心跳，时刻看到服务在线
          enabled: true
